on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: dew-web
          token: ${{ secrets.PAT }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type": "build", "section": "Build System", "hidden": false}]'
